<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <InternalsVisibleTo Include="Servus.Akka.Tests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Hosting"/>
        <PackageReference Include="Akka.Streams"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Servus"/>
        <None Include="../../README.md" Pack="true" Visible="false" PackagePath="\"/>
<None Include="../../LICENSE" Pack="true" Visible="false" PackagePath="\"/>
    </ItemGroup>

    <Target Name="ServusLogo" BeforeTargets="Build">
        <Message Text=" " Importance="high"/>
        <Message Text=" " Importance="high"/>
        <Message Text="                                   /\" Importance="high"/>
        <Message Text="                                  /  \" Importance="high"/>
        <Message Text="                                 /    \__" Importance="high"/>
        <Message Text="                           /\   /        \    /\" Importance="high"/>
        <Message Text="                          /  \_/          \__/  \" Importance="high"/>
        <Message Text="                         /                       \" Importance="high"/>
        <Message Text="                        /_________________________\" Importance="high"/>
        <Message Text="                                  servus!" Importance="high"/>
        <Message Text=" " Importance="high"/>
        <Message Text=" " Importance="high"/>
    </Target>
</Project>
