<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Akka.TestKit.Xunit"/>
        <PackageReference Include="Akka.Streams.TestKit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Servus.Akka\Servus.Akka.csproj"/>
        <ProjectReference Include="..\Servus.Akka.TestKit\Servus.Akka.TestKit.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="xunit.runner.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
